// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Siniestros.Infrastructure.Persistence;

#nullable disable

namespace Siniestros.Infrastructure.Migrations
{
    [DbContext(typeof(SiniestrosDbContext))]
    partial class SiniestrosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Siniestros.Domain.Entities.Ciudad", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.Property<string>("IdDepartamento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartamento", "Nombre")
                        .IsUnique();

                    b.ToTable("Ciudad", (string)null);
                });

            modelBuilder.Entity("Siniestros.Domain.Entities.Departamento", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Departamento", (string)null);
                });

            modelBuilder.Entity("Siniestros.Domain.Entities.Siniestro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdCiudad")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.Property<int>("IdTipoSiniestro")
                        .HasColumnType("int");

                    b.Property<int>("NumeroVictimas")
                        .HasColumnType("int");

                    b.Property<int>("VehiculosInvolucrados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora");

                    b.HasIndex("IdCiudad");

                    b.HasIndex("IdTipoSiniestro");

                    b.ToTable("Siniestros", (string)null);
                });

            modelBuilder.Entity("Siniestros.Domain.Entities.TipoSiniestro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoSiniestro", (string)null);
                });

            modelBuilder.Entity("Siniestros.Domain.Entities.Ciudad", b =>
                {
                    b.HasOne("Siniestros.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Ciudades")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Siniestros.Domain.Entities.Siniestro", b =>
                {
                    b.HasOne("Siniestros.Domain.Entities.Ciudad", "Ciudad")
                        .WithMany("Siniestros")
                        .HasForeignKey("IdCiudad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Siniestros.Domain.Entities.TipoSiniestro", "TipoSiniestro")
                        .WithMany("Siniestros")
                        .HasForeignKey("IdTipoSiniestro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ciudad");

                    b.Navigation("TipoSiniestro");
                });

            modelBuilder.Entity("Siniestros.Domain.Entities.Ciudad", b =>
                {
                    b.Navigation("Siniestros");
                });

            modelBuilder.Entity("Siniestros.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Siniestros.Domain.Entities.TipoSiniestro", b =>
                {
                    b.Navigation("Siniestros");
                });
#pragma warning restore 612, 618
        }
    }
}
